global using Api.Controllers;
global using Api.Helpers;
global using Common.Entities;
global using Common.Models;
global using Common.Models.Customer;
global using Common.Models.Pizza;
global using Core;
global using DataAccess;
global using Microsoft.AspNetCore.Mvc;