<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<CodeAnalysisRuleSet>$(ProjectDir)..\StyleCopRuleSet.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Entities\" />
	</ItemGroup>

	<ItemGroup>
        <PackageReference Include="Riok.Mapperly" Version="3.6.0" />
	  <PackageReference Include="FluentValidation" Version="12.1.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7" />
	  <PackageReference Include="Serilog" Version="4.3.1" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	  <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>
</Project>