<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<CodeAnalysisRuleSet>$(ProjectDir)..\StyleCopRuleSet.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="FluentValidation" Version="12.0.0" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
	  <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Scrutor" Version="6.1.0" />
	  <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataAccess\DataAccess.csproj" />
	</ItemGroup>
</Project>