<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="Aspire.AppHost.Sdk" Version="13.0.0" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.3.0" />
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.3.0" />
        <PackageReference Include="OpenTelemetry" Version="1.15.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Api\Api.csproj" />
        <ProjectReference Include="..\DbUp.Migrations\DbUp.Migrations.csproj" />
        <ProjectReference Include="..\Mcp\Mcp.csproj" />
    </ItemGroup>
</Project>
