<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core.Contracts\Core.Contracts.csproj" />
	  <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Scrutor" Version="6.1.0" />
	</ItemGroup>
</Project>