<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataAccess\DataAccess.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Customer\Commands\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="FluentValidation" Version="12.1.1" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
	  <PackageReference Include="Scrutor" Version="7.0.0" />
	</ItemGroup>
</Project>