name: .NET - Phase 2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore "./Phase 2/src/02. EndSolution/sln"
    - name: Build
      run: dotnet build "./Phase 2/src/02. EndSolution/sln" --configuration Release --no-restore
