name: .NET - Phase 6 - Final Solution

on:
    push:
        branches: [ main, master ]
        paths:
            - "Phase 6/**"
            - ".github/workflows/dotnet-phase6-finalsolution.yml"
    pull_request:
        branches: [ main, master ]
        paths:
            - "Phase 6/**"
            - ".github/workflows/dotnet-phase6-finalsolution.yml"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 10.0.x
            - name: Install dependencies
              run: dotnet restore "./Phase 6/src/03. Step 2/Pezza.slnx"
            - name: Build
              run: dotnet build "./Phase 6/src/03. Step 2/Pezza.slnx" --configuration Release
                  --no-restore
