name: .NET - Phase 8 - Step 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore "./Phase 8/src/02. Step 1/Pezza.sln"
    - name: Build
      run: dotnet build "./Phase 8/src/02. Step 1/Pezza.sln" --configuration Release --no-restore
