name: .NET - Phase 6 - Step 1

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.100-preview.7.24407.12
            - name: Install dependencies
              run: dotnet restore "./Phase 6/src/02. Step 1/EList.sln"
            - name: Build
              run: dotnet build "./Phase 6/src/02. Step 1/EList.sln" --configuration Release --no-restore
