name: .NET - Phase 5 - Start Solution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore "./Phase 5/src/01. StartSolution/Pezza.slnx"
      - name: Build
        run: dotnet build "./Phase 5/src/01. StartSolution/Pezza.slnx" --configuration
          Release --no-restore
