name: .NET - Phase 6 - Step 4

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 9.0.x
                  dotnet-quality: "preview"
            - name: Install dependencies
              run: dotnet restore "./Phase 6/src/04. Step 4/EList.sln"
            - name: Build
              run: dotnet build "./Phase 6/src/04. Step 4/EList.sln" --configuration Release --no-restore
